lista_de_tareas/auth_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login" ),
    path('logout/', views.LogoutView, name="logout"),
    path('register/', views.RegisterView.as_view(), name='register'),

]

lista_de_tareas/lista_de_tareas/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index_app.urls')),
    path('auth/', include('auth_app.urls')),
    path('tasks/', include('task_app.urls'))
]

lista_de_tareas/task_app/urls.py
from django.urls import path
from .views import TaskListView, TaskItemView, TaskCreationView, TaskEditionView


urlpatterns = [
    path('tasks_list', TaskListView.as_view(), name="tasks_list"),
    path('task/<int:pk>/', TaskItemView.as_view(), name="task_item"),
    path('task_creation/', TaskCreationView.as_view(), name="task_creation"),
    path('task_edit/<int:pk>/', TaskEditionView.as_view(), name="task_edition"),
]

lista_de_tareas/task_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Label(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=25)
    description = models.TextField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.title
    
class Priority(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=25)
    rank = models.IntegerField()
    description = models.TextField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.title
    
class Task(models.Model):
    STATUS_CHOICE = [
          ('Pendiente', 'Pendiente'),
          ('En Progreso', 'En progreso'),
          ('Completada', 'Completada')
    ]
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=150)
    description = models.TextField()
    due_date = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=15, choices=STATUS_CHOICE)
    label = models.ForeignKey(Label, verbose_name=("etiqueta"), on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    priority = models.ForeignKey(Priority, null=True, blank=True, on_delete=models.SET_NULL)

    def formatted_due_date(self):
            return self.due_date.strftime("%d-%m-%Y")
    
    def __str__(self):
        return self.title
    

class TaskObservation(models.Model):
    observation = models.TextField()
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    def __str__(self):
        return self.observation
    

lista_de_tareas/task_app/forms.py
import datetime
from django import forms
from .models import Label, Priority, Task, TaskObservation


class TaskFilterForm(forms.Form):
    STATUS_CHOICES = [
        ('all_status', 'Cualquier Estado'),
        ('Pendiente', 'Pendiente'),
        ('En Progreso', 'En Progreso'),
    ]

    max_due = forms.DateField(label='Fecha límite máxima', required=False, widget=forms.DateInput( attrs={'type': 'date', 'class': 'form-control', 'placeholder': 'Fecha límite máxima'}))
    

    extra_option = [('all_tasks', 'Todas las etiquetas')]
    labels = Label.objects.all()
    choices = extra_option + [(label.id, label.title) for label in labels]
    
    extra_option_priority = [('all_priority', 'Cualquier prioridad')]
    priority = Priority.objects.all()
    choices_priority = extra_option_priority + [(prior.id, prior.title) for prior in priority]



    label = forms.TypedChoiceField(choices=choices, required=False)
    status = forms.ChoiceField(label='Estado', choices=STATUS_CHOICES, required=False)
    priority = forms.TypedChoiceField(choices=choices_priority, required=False)

class TaskForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = 'Título'
        self.fields['description'].label = 'Descripción'
        self.fields['due_date'].label = 'Fecha límite'
        self.fields['status'].label = 'Estado'
        self.fields['label'].label = 'Etiqueta'
        self.fields['user'].label = 'Usuario a asignar'
        self.fields['priority'].label = 'Prioridad'


        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['description'].widget.attrs['class'] = 'form-control'
        self.fields['description'].widget.attrs['rows'] = '5'
        self.fields['due_date'].widget.attrs['class'] = 'form-control'
        self.fields['due_date'].widget = forms.DateInput(attrs={'type': 'date'})
        self.fields['status'].widget.attrs['class'] = 'form-control'
        self.fields['label'].widget.attrs['class'] = 'form-control'
        self.fields['user'].widget.attrs['class'] = 'form-control'
        self.fields['priority'].widget.attrs['class'] = 'form-control'

        instance = kwargs.get('instance')
        if instance and 'due_date' in self.initial:
            due_date = instance.due_date
            if due_date:
                self.initial['due_date'] = due_date.strftime('%Y-%m-%d')
            else: pass
 

    class Meta:
        model = Task
        fields = ['title', 'description', 'due_date', 'status', 'label', 'priority', 'user']


class ObservationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ObservationForm, self).__init__(*args, **kwargs)
        self.fields['observation'].label = 'Observación'

        self.fields['observation'].widget.attrs['class'] = 'form-control'
        self.fields['observation'].widget.attrs['rows'] = '3'
    class Meta:
        model = TaskObservation
        fields = ['observation']

lista_de_tareas/task_app/views.py
from datetime import datetime
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from .models import Priority, Task, Label, TaskObservation
from .forms import TaskFilterForm, TaskForm, ObservationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

@method_decorator(login_required, name='dispatch')
class TaskListView(View):

    """
     Shows the list of pending tasks.
     Post method filter the items acording to the parameters specified by user
    """

    template = "tasks_list.html"
    labels = Label.objects.all()
    form = TaskFilterForm
    prioritys = Priority.objects.all()

    def dispatch(self, request, *args, **kwargs):
        self.usuario = request.user
        self.completed_tasks = Task.objects.filter(user_id=self.usuario.id, status='Completada').order_by('due_date')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        tasks = Task.objects.filter(user_id=self.usuario.id).exclude(status='Completada').order_by('due_date')
        context = {'tasks': tasks,
                   'labels': self.labels,
                   'form': self.form,
                   'completed_tasks' : self.completed_tasks}
        return render(request, self.template, context)

    def post(self, request):
        label = request.POST['label']
        status = request.POST['status']
        priority = request.POST['priority']
        max_due = request.POST['max_due']

        if label == "all_tasks":
            filtered_tasks = Task.objects.filter(user_id=self.usuario.id).exclude(status='Completada').order_by('due_date')
        else:
            filtered_tasks = Task.objects.filter(user_id=self.usuario.id, label=label).exclude(status='Completada').order_by('due_date')

        if status == "all_status":
            pass
        else:
             filtered_tasks = filtered_tasks.filter(status=status)

        if priority == "all_priority":
            pass
        else:
             filtered_tasks = filtered_tasks.filter(priority=priority)

        if max_due:
            max_due = datetime.strptime(max_due, '%Y-%m-%d').date()
            filtered_tasks = filtered_tasks.filter(due_date__lt=max_due)

        context = {'tasks' : filtered_tasks,
                    'labels' : self.labels,
                    'form' : self.form,
                    'completed_tasks' : self.completed_tasks}

        if label != "all_tasks":
            context['requested_label'] = int(label)

        if priority != "all_priority":
            context['requested_priority'] = int(priority)
            context['priority'] = self.prioritys

        return render(request, self.template, context)


@method_decorator(login_required, name ='dispatch')
class TaskItemView(View):

    """
    Shows in a card a certain item requested by the user
    """

    template = "task_item.html"
    observation_form = ObservationForm
    
    def dispatch(self, request, *args, **kwargs):
        self.usuario = request.user
        self.task = get_object_or_404(Task, pk=kwargs['pk'])
        if self.task.user != self.usuario:
            return HttpResponseForbidden("No tienes permiso para acceder a esta tarea.")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        observations = TaskObservation.objects.filter(task_id=self.task.id)
        context = {'task' : self.task,
                    'observations' : observations,
                    'form' : self.observation_form}
        return render(request, self.template, context)
    
    def post(self, request, *args, **kwargs):
        if 'complete' in request.POST:
            self.task.status = 'Completada'
            self.task.save()
        elif 'delete_task' in request.POST:
            self.task.delete()
        elif "observation" in request.POST:
            form = self.observation_form(request.POST)
            if form.is_valid():
                observation = form.save(commit=False)
                observation.task = self.task
                observation.save()
                return redirect(request.get_full_path())
        elif "delete_observation" in request.POST:
            observation_id = request.POST.get('delete_observation')
            observation = get_object_or_404(TaskObservation, id=observation_id)
            observation.delete()
            return redirect(request.get_full_path())
        return redirect('tasks_list')


@method_decorator(login_required, name ='dispatch')
class TaskCreationView(View):

    """
    Create a new task object    
    """
    form = TaskForm
    template = "task_edit.html"
    title = "Agregar Tarea"

    def get(self, request):
        form = self.form
        context = {'form' : form,
                   'title' : self.title}
        return render(request, self.template, context)
    
    def post(self, request):
        form = self.form(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks_list')
        context = {'form': form,
                   'title' : self.title}
        return render(request, self.template, context)


@method_decorator(login_required, name ='dispatch')
class TaskEditionView(View):

    """
    Updates an specific task
    """

    template = "task_edit.html"
    form = TaskForm
    title = "Editar Tarea"

    def dispatch(self, request, *args, **kwargs):
        self.task = get_object_or_404(Task, pk=kwargs['pk'])
        if self.task.user != request.user:
            return HttpResponseForbidden("No tienes permiso para acceder a esta tarea.")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form(instance=self.task, initial={'due_date': self.task.due_date})
        context = {
            'task': self.task,
            'form': form,
            'title': self.title}
        return render(request, self.template, context)

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST, instance=self.task)
        if form.is_valid():
            task = form.save(commit=False)
            task.user_id = request.user.id
            task.save()
            return redirect('task_item', pk=self.task.pk)
        context = {
            'form': form,
            'title': self.title}
        return render(request, self.template, context)

lista_de_tareas/task_app/templates/task_edit.html
{% extends 'base.html' %} {% load static %} 
{% block title %}{{ title }}{% endblock %}
{% block content %} {% block header %}{% endblock %}
<div class="row justify-content-center">
  <a href={% if title == "Editar Tarea" %}" {% url 'task_item' task.id %}" {% else %} "{% url 'tasks_list' %}" {% endif %} class="btn btn-light rounded-3 col-lg-2 m-2"
    >Regresar</a>
</div>
<div class="row justify-content-center">
  <div class="card text-dark bg-light mt-2 mb-3 col-lg-6">
    <div class="card-body d-flex justify-content-between">
      <span class="card-title h5 p-2 rounded-3 my-2 cursor">{{ title }}</span>
    </div>
    <form class="card p-3 m-2 bg-description rounded-3" method="POST">
      {% csrf_token %} {{ form.as_p}}
      <button type="submit" class="btn btn-primary my-2">Guardar</button>
    </form>
    <div class="card-body d-flex justify-content-between"></div>
  </div>
</div>
{% endblock %} 

lista_de_tareas/task_app/templates/task_item.html
{% extends 'base.html' %} {% load static %}
{% block title %}Tarea {{ task }}{% endblock %} 
{% block content %} {% block header %}{% endblock %}
<div class="row justify-content-center">
   
  <form method="POST">
    {% csrf_token %}
    <div class="d-flex justify-content-center">
  <a href="{% url 'task_edition' task.id %}" class="btn btn-primary rounded-3 col-lg-2 m-2">Editar Tarea</a>
  <button type="submit" name="complete" class="btn btn-success rounded-3 col-lg-2 m-2">Completar Tarea</button>
  
  <button
    type="button"
    class="btn btn-danger rounded-3 col-lg-2 m-2"
    data-bs-toggle="modal"
    data-bs-target="#deleteModal"
  >
    Eliminar Tarea
  </button>
  <a href="{% url 'tasks_list' %}" class="btn btn-light rounded-3 col-lg-2 m-2"
    >Regresar</a>
</div>
  </form>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Confirmar eliminación</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            ¿Está seguro de querer eliminar la tarea? <br> Esta no podrá ser recuperada...
        </div>
        <form method="post" name="delete_task"> 
            {% csrf_token %}
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Volver</button>
              <button type="submit" class="btn btn-danger">Eliminar Tarea</button>
            </div>
        </form>
      </div>
    </div>
  </div>


  
</div>
{% if task.priority %}
<div class="row justify-content-center">
  <div class="card text-dark mt-2 mb-3 col-lg-6
                                                {% if task.priority.rank == 1 %}
                                                priority-low
                                                {% elif task.priority.rank == 2 %}
                                                priority-medium latente1
                                                {% else %}
                                                priority-high latente2
                                                {% endif %}">
    <div class="card-body d-flex justify-content-center">
      <span class="card-title h2 p-2 rounded-3 my-2 cursor">Prioridad: {{ task.priority }}</span>
    </div>
  </div>
</div>
{% endif %}
<div class="row justify-content-center">
  <div class="card text-dark bg-light mt-2 mb-3 col-lg-6 hovered">
    <div class="card-body d-flex justify-content-between">
      <span class="card-title h5 p-2 rounded-3 my-2 cursor">{{ task }}</span>
      <span
        class="{% if task.label_id == 1 %}bg-primary text-white {% elif task.label_id == 2 %}bg-success text-white {% elif task.label_id == 3 %}bg-warning {% elif task.label_id == 4 %}bg-light {% else %}bg-danger text-white {% endif%} p-2 rounded-3 my-2 hovered cursor"
        data-bs-toggle="tooltip"
        data-bs-placement="bottom"
        title="{{ task.label.description }}"
        >{{ task.label.title}}</span>
    </div>
    <div class="p-3 m-2 bg-description rounded-3">
      <p class="card-text cursor">{{ task.description }}</p>
    </div>
    {% if observations %}
    <form method="POST">
    {% csrf_token %}
    <p class="mx-3">Observaciones:</p>
    {% for observation in observations %}
    <div class="p-3 mx-2 mb-2 bg-description rounded-3 d-flex justify-content-between">
      <span class="card-text m-2 cursor">{{ observation }}</span>
      <button type="submit" name="delete_observation" value="{{ observation.id }}" class="btn btn-success rounded-3 col-lg-2 align-self-start align-self-center">Eliminar</button>
    </div>
    {% endfor %}
    </form>
    {% endif %}
    <div class="card-body d-flex justify-content-between">
      <span class="bg-date p-2 py-3 rounded-3 cursor"
        >{% if task.due_date %}{{ task.due_date }}{% else %}Sin fecha límite{% endif %}</span
      >
      <span class="bg-status p-2 py-3 rounded-3 cursor">{{ task.status }}</span>
    </div>
  </div>
</div>
<div class="row justify-content-center">
  <div class="card text-dark bg-light mt-2 mb-3 col-lg-6">
    <div class="card-body d-flex justify-content-between">
      <span class="card-title h5 p-2 rounded-3 my-2 cursor">Agregar Observación</span>
    </div>
    <form class="card p-3 m-2 bg-description rounded-3" method="POST" name="observation">
      {% csrf_token %} {{ form.as_p}}
      <button type="submit" class="btn btn-primary my-2">Guardar</button>
    </form>
    <div class="card-body d-flex justify-content-between"></div>
  </div>
</div>

{% endblock %} 

lista_de_tareas/task_app/templates/tasks_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Lista de Tareas {{ user.username }}{% endblock %}

{% block content %}
{% block header %}<h1 class="titulo">Tareas Pendientes</h1>{% endblock %}

<div class="row d-flex justify-content-between">
<form class="card col-12 col-lg-9 p-2 d-flex" method="POST">
  {% csrf_token %}
  <div class="d-flex">
    <select class="form-select m-2" name="label">
      {% for option_value, option_label in form.choices %}
      <option value="{{ option_value }}" {% if field.value == option_value %}selected{% endif %}>{{ option_label }}</option>
      {% endfor %}
    </select>
    <select class="form-select m-2" name="status">
      {% for option_value, option_label in form.STATUS_CHOICES %}
      <option value="{{ option_value }}" {% if field.value == option_value %}selected{% endif %}>{{ option_label }} </option>
      {% endfor %}
    </select>
    <select class="form-select m-2" name="priority">
      {% for option_value, option_label in form.choices_priority %}
      <option value="{{ option_value }}" {% if field.value == option_value %}selected{% endif %}>{{ option_label }}</option>
      {% endfor %}
    </select>
    <input type="date" name="max_due" class="form-control m-2" placeholder="Fecha límite máxima" id="id_max_due">
    <button type="submit" class="btn btn-primary my-2">Filtrar</button>
  </div>
</form>
<a href="task_creation" class="col-11 col-lg-2 btn btn-success rounded-3 my-2 mx-3"><p class="my-2 h5">Agregar Tarea</p></a>
</div>



<br>

{% if tasks %}
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
              <th scope="col">Detalle</th>
              <th scope="col">Tarea</th>
              <th scope="col">Descripción</th>
              <th scope="col">Estado</th>
              <th scope="col">Prioridad</th>
              <th scope="col">Fecha Límite</th>
            </tr>
          </thead>
          <tbody>
            {% for task in tasks %}
            <tr class="{% if task.label_id == 1 %}table-primary
                        {% elif task.label_id == 2 %}table-success
                        {% elif task.label_id == 3 %}table-warning
                        {% elif task.label_id == 4 %}table-light
                        {% else %}table-danger {% endif%} align-middle cursor" >
                <td><a href="{% url 'task_item' task.id %}" class="btn btn-dark">Ver Tarea</a></td>
                <th class="align-middle cursor">{{ task.title }}</th>
                <td class="align-middle cursor" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ task.description }}">{{ task.description|truncatechars:30 }}</td>
                <td class="align-middle cursor">{{ task.status }}</td>
                <td class="align-middle cursor"><span class="p-2 rounded-3 {% if task.priority.rank == 1 %}
                                                              priority-low
                                                              {% elif task.priority.rank == 2 %}
                                                              priority-medium
                                                              {% elif task.priority.rank == 3 %}
                                                              priority-high
                                                              {% endif %}">
                  {% if task.priority %}{{ task.priority }}{% else %}No asignada{% endif %}</span></td>
                <td class="align-middle cursor" ><span class="bg-date p-2 rounded-3">{% if task.due_date %}{{ task.due_date }}{% else %}Sin fecha límite{% endif %}</span></td>
            </tr>
            {% endfor %}
          </tbody>
    </table>
  </div>
<br>
<span class="h5 m-2">Etiquetas:</span> <br><br>
{% for label in labels %}
<span class="{% if label.id == 1 %}bg-primary text-white
{% elif label.id == 2 %}bg-success text-white
{% elif label.id == 3 %}bg-warning
{% elif label.id == 4 %}bg-light
{% else %}bg-danger text-white {% endif%} p-2 rounded-3 my-2 hovered cursor"data-bs-toggle="tooltip" data-bs-placement="bottom" title="{{ label.description }}">{{ label }}</span>
{% endfor %}
{% else %}
    {% if requested_label %}
    <p class="text-center h1 text-success my-2 mb-5 latente cursor">¡No hay tareas pendientes con la etiqueta {% for label in labels %}{% if label.id == requested_label %}{{ label }}{% endif %}{% endfor %}!</p>
    {% elif requested_priority %}
    <p class="text-center h1 text-success my-2 mb-5 latente cursor">¡No hay tareas de prioridad {% for prior in priority %}{% if prior.id == requested_priority %}{{ prior }}{% endif %}{% endfor %} pendientes!</p>
    {% else%}
  <p class="text-center h1 text-success my-2 mb-5 latente cursor">¡No hay tareas pendientes!</p>
{% endif %}
{% endif %}
<br><br>
{% if completed_tasks %}
<h2 class="titulo h1">Tareas Completadas</h2>
<div class="table-responsive">
  <table class="table table-hover">
      <thead>
          <tr>
            <th scope="col">Detalle</th>
            <th scope="col">Tarea</th>
            <th scope="col">Descripción</th>
            <th scope="col">Estado</th>
            <th scope="col">Fecha Límite</th>
          </tr>
        </thead>
        <tbody>
          {% for task in completed_tasks %}
          <tr class="{% if task.label_id == 1 %}table-primary
                      {% elif task.label_id == 2 %}table-success
                      {% elif task.label_id == 3 %}table-warning
                      {% elif task.label_id == 4 %}table-light
                      {% else %}table-danger {% endif%} align-middle cursor" >
              <td><a href="{% url 'task_item' task.id %}" class="btn btn-dark">Ver Tarea</a></td>
              <th class="align-middle cursor">{{ task.title }}</th>
              <td class="align-middle cursor" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ task.description }}">{{ task.description|truncatechars:30 }}</td>
              <td class="align-middle cursor">{{ task.status }}</td>
              <td class="align-middle cursor" ><span class="bg-date p-2 rounded-3">{% if task.due_date %}{{ task.due_date }}{% else %}Sin fecha límite{% endif %}</span></td>
          </tr>
          {% endfor %}
        </tbody>
  </table>
</div>
{% endif %}

{% endblock %}